### ISSUE TITLE
Remote registry

### ISSUE THREAD

**Issue by DavidMinarsch** [valory-xyz/open-aea#1]
**Is your feature request related to a problem? Please describe.**
The hard coded remote registry present in fetchai/agents-aea's aea has been removed. At the moment the registry api url is fetched from global aea config file. By default this is set to None.

Tests which rely on the remote registry are currently skipped. You can find them by searching for: ```@pytest.mark.skip  # need remote registry```

**Describe the solution you'd like**
It would be desirable to set different kind of remote registries. Two kinds should be supported: legacy fetchai registry type and ipfs registry.

**Comment by angrybayblade** [comment]
Addressed #532
