### ISSUE TITLE
version consistency in workflow.yml 

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-aea#105]
all versions should be the same throughout:

- either `actions/setup-python@master` or `actions/setup-python@v3`
- either `actions/setup-go@master` or `actions/setup-go@v3`
- `go-version: ">=1.14.0 <=1.17.7"`  # range known to work

**Comment by DavidMinarsch** [comment]
I suggest pinning exact versions or ranges, so `actions/setup-python@v3`, for all dev related activities.
