### ISSUE TITLE
Implement debug mode similar to Flask debug mode

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-aea#16]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I have to tear down and then spin up an agent I am developing.

**Describe the solution you'd like**
It would be super cool if the agents reloaded themselves upon file changes if in a debug mode.
i.e. if there was a flag so I could go
aea run -m DEBUG
Then, the agents would watch the its own files and on any changes to code, it would reload this code and start again.

**Describe alternatives you've considered**
1. TDD kind of makes this obsolete

(This was a feature request from a dev I work with on the aea framework.)

**Comment by DavidMinarsch** [comment]
Not sure how this would work. Where should the AEA start running? From the beginning, from where it restarts? In the later case, the file changes might make this impossible as the changes could remove that execution path.

I agree better debugging is needed but I am not sure this approach is the right way to do it.

If you've got ideas how to do it then please share :)

**Comment by 8ball030** [comment]
@DavidMinarsch @mohandast52 Pretty that developer mode closes this.
