### ISSUE TITLE
Investigate and fix click CLIRunner stdout capture issues

### ISSUE THREAD

**Issue by angrybayblade** [valory-xyz/open-aea#171]
https://github.com/valory-xyz/open-aea/runs/6787538280?check_suite_focus=true

**Comment by Karrenbelt** [comment]
would be good to have some actual examples of tests, please record logs in a text file and attach to issue next time (CI run has expired)

some potentially useful links:
https://stackoverflow.com/questions/65967420/pytest-how-can-i-blindly-run-any-subprocess-and-capture-all-output
https://www.scivision.dev/pytest-stderr-capture/
https://stackoverflow.com/questions/63233049/running-a-subprocess-fails-when-not-using-pytest-no-capture

and an interesting code snippet
https://github.com/valory-xyz/open-aea/blob/4c4156a58135184f3d86b81f00144a80674e8148/tests/common/utils.py#L381-L396

**Comment by Karrenbelt** [comment]
It appears that `capfd` and `capsys` cannot capture stdout in tests using `ClickCliRunner` because of the because of the isolation context manager
https://github.com/valory-xyz/open-aea/blob/4c4156a58135184f3d86b81f00144a80674e8148/aea/test_tools/click_testing.py#L59)

**Comment by DavidMinarsch** [comment]
Closed without direct resolution

**Comment by Karrenbelt** [comment]
now addresses here: https://github.com/valory-xyz/open-aea/pull/459
