### ISSUE TITLE
test_run_with_profiling is flaky

### ISSUE THREAD

**Issue by dvilelaf** [valory-xyz/open-aea#177]
The test_run_with_profiling test was marked as flaky in the past for python < 3.7, but even for python 3.7 and 3.8 is problematic. See https://github.com/valory-xyz/open-aea/pull/130#issuecomment-1106705879. Almost any change to the test, or a change to the profiler will make it fail with AttributeError: 'list' object has no attribute 'items'. Seems like a pytest issue.

**Comment by Karrenbelt** [comment]
Investigated the issue locally. I observe no failure on python 3.7 after running 100 times. I tried changing directories as comment on PR references suggests, also nothing changes or break. The `pytest.mark.skip` is already no longer there. The flakiness can be addressed easily, also for the other 11 tests marked as flaky, with proposed CliTest tool in PR #472.
