### ISSUE TITLE
Improve 

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-aea#182]
**Is your feature request related to a problem? Please describe.**

Presently, the aea framework is unable to handle yaml format in terms of config overrides.

This is as we only presently parse json like strings.

However this is incompatible with the yaml formatting we use throughout the definitions of our components.

Please revert https://github.com/valory-xyz/consensus-algorithms/pull/913 

upon completion of this ticket as this will then remove the need for this.

Revert the please reference to revert #913 when this has been fixed on open-aea

**Describe the solution you'd like**

The ability to parse yaml like overrides as yaml so that we are able to specify lists and dictionary in yaml from 

```
aea config set skill example.connections.http_echo ['test', 'test'] 

```

**Additional context**

**Comment by angrybayblade** [comment]
Addressed here https://github.com/valory-xyz/open-aea/pull/284
