### ISSUE TITLE
Connection configuration can't be accessed from Behaviour.

### ISSUE THREAD

**Issue by dvilelaf** [valory-xyz/open-aea#195]
**Is your feature request related to a problem? Please describe.**
Connection configuration can't be accessed from a Behaviour since it is not in the context. It could be useful to know things like gas strategy configuration so transaction settlement has more context when triggering repricing.

**Describe the solution you'd like**
Make connection config available to behaviours.

**Comment by DavidMinarsch** [comment]
The gas strategy set on the connection is the default gas strategy. It should also be possible for the skill to programmatically override this on a per message basis.
