### ISSUE TITLE
Add functionality to remove package from local registry ( IPFS ).

### ISSUE THREAD

**Issue by angrybayblade** [valory-xyz/open-aea#21]
**Is your feature request related to a problem? Please describe.**
We have the functionality to publish a package to the local ipfs registry but there is no way to remove it from the local registry.

**Describe the solution you'd like**
Add CLI command in the aea-cli-ipfs plugin to remove the package from the local registry.

**Comment by DavidMinarsch** [comment]
This is no longer relevant after merge of #102
