### ISSUE TITLE
Might not be an issue - needs checking

### ISSUE THREAD

**Issue by DavidMinarsch** [valory-xyz/open-aea#254]
**Is your feature request related to a problem? Please describe.**
I'm not sure if it is present or not.

**Describe the solution you'd like**
When loading aea-config.yaml, we should ensure that it references ALL the package dependencies, even nested ones. So that `aea-config.yaml` is always flat.

The non-agent packages should always be non-flat: https://github.com/valory-xyz/open-aea/issues/253

**Comment by marcofavorito** [comment]
It seems that the framework is already able to detect missing packages from `aea-config.yaml`, as adding a package with missing dependencies will cause an error:

![image](https://user-images.githubusercontent.com/9467617/183290369-ea60d0a0-8ca4-4122-adc8-e13f65dbc400.png)

**Comment by DavidMinarsch** [comment]
Ok, that's because the aea add commands correctly populate the aea-config. But take [this PR](https://github.com/valory-xyz/agent-academy-1/pull/110/files) where some dependencies are not mentioned in aea-config, but of course they are mentioned indirectly as dependencies of referenced dependencies. My point is that the aea-config, should flatten the tree and contain ALL dependencies, even indirect ones!

**Comment by DavidMinarsch** [comment]
Note, above PR passes tests, as do the commits preceding this PR. Suggesting we miss some checks somewhere.
