### ISSUE TITLE
Load CLI config as a part of the context object

### ISSUE THREAD

**Issue by angrybayblade** [valory-xyz/open-aea#256]
**Is your feature request related to a problem? Please describe.**
We use glocal CLI config on so many places so Instead of calling a load function everywhere we load and store the global CLI config as a part of the context object at the beginning

**Describe the solution you'd like**
Load and store the CLI config as object on Context class

**Comment by DavidMinarsch** [comment]
This is a general refactor idea - closing as it is better discussed in a wider context
