### ISSUE TITLE
aea environmental vars and `--aev` flag

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-aea#263]
For a user / developer perspective the error that we throw when the --aev flag is missed when using the CLI tool could be clearer. I know Ardian ran into this and "got rid of them like a neanderthal".
```
ValueError: Trying to replace value '1337' with value '${CONNECTION_LEDGER_CONFIG_LEDGER_APIS_ETHEREUM_CHAIN_ID:int:31337}' which is of different type.
```
We could be more explicit in the specific data type mismatch, and provide a hint to use the `--aev` flag in case of environmental variables
```
ValueError: Trying to replace value '1337' of type 'int' with value '${CONNECTION_LEDGER_CONFIG_LEDGER_APIS_ETHEREUM_CHAIN_ID:int:31337}' which is of type 'str'. If you are using environmental variables as overwrites, make sure to use the `--aev` flag.
```
At times one might need to provide this flag to multiple commands, e.g. `aea issue-certificates --aev && aea run --aev`

Alternatively, we can detect patterns of environmental variable-specification in the configuration files, and run `--aev` mode whenever these are detected without the need for specification via CLI by the user.

**Comment by DavidMinarsch** [comment]
What's the risk of making `aev` the default mode?
