### ISSUE TITLE
Contract class `ledger_api` and `contract_address` arguments

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-aea#265]
The [Contract](https://github.com/valory-xyz/open-aea/blob/e4a3150ca5c92f05ba2b4cdad26532967ffa91fe/aea/contracts/base.py#L54) interface requires passing `ledger_api` and `contract_address` as arguments to many functions, whereas for any concrete implementation of a contract inheriting from this base class these will be constant; a contract will exist on a specific ledger at a specific address for as long as the blockchain exists. Passing them as arguments is therefor not useful, can lead to inconsistencies of ever the arguments are passed are not constant, and decreases ease of implementation and legibility of code.

The suggested solution is to implement these two arguments on initialization and reference them within the methods instead. This way we can have a single generic class that represents the contract, and a instances that represent their representation on a specific chain under a specific address. Various methods on this class should become regular (instance) methods instead of classmethods.

Since the proposed change leads to backwards incompatibility, the change is suggested when we transition to version 2.0.0

P.S.
"we pay attention to have the same bytecode on each chain, and this is the right way to do that" - Kupermind
"well we may. But we don't only interact with our own contracts now do we?" - self

The Keep3rV1 contract, for example, has the same ABI on mainnet as on Goerli, but different byte code. Also, the address may or may not be same on a different chain. Passing the ledger and address on class Instantiation makes perfect sense as it mimics exactly what happens on-chain when a contract is deployed.

**Comment by angrybayblade** [comment]
Contracts can have same byte code at different addresses on same chain and also contact class is never instantiated in framework
