### ISSUE TITLE
smart contract bytecode library linking

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-aea#266]
**Is your feature request related to a problem? Please describe.**

Library dependencies present in smart contracts and their bytecode are an issue when trying to deploy them. Such features need to be processed and replaced with the on-chain address of the corresponding library. This is referred to as [library linking](https://docs.soliditylang.org/en/v0.7.5/using-the-compiler.html?highlight=library#library-linking)

It will be important to have a means to obtain the library contract address in order to replace the bytecode where needed.

This issue was first encountered as part of the Keep3r system, and [this PR](https://github.com/valory-xyz/agent-academy-2/pull/74) showcases how to this can be addressed and shows a partial implementation of the tool  

**Describe the solution you'd like**
As access to the other repository is not guaranteed, shamelessly plagiarized myself: [library_linking.txt](https://github.com/valory-xyz/open-aea/files/9363253/library_linking.txt)

**Describe alternatives you've considered**
ethpm [LinkableContract](https://web3py.readthedocs.io/en/stable/ethpm.html#linkablecontract). This requires a specific format of the package for import before this can be used. One should definitely look at their code and use what is needed as a template.

**Additional context**

**Comment by DavidMinarsch** [comment]
I would consider this clearly outside the scope of open-aea or even open-autonomy. Both take finished smart contracts and wrap them.
