### ISSUE TITLE
remove agent termination logic from `BaseAEATestCase.missing_from_output`

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-aea#337]
https://github.com/valory-xyz/open-aea/blob/05039769d62c28a9b1ce7209b27d44e2bbefe568/aea/test_tools/test_cases.py#L856-L900

this has lead to unexpected issue on open-autonomy before where one agent is waiting for another to respond, however, that agent already terminated. The issue being that it's not intuitive to that the agent might be terminated, particularly since the default is set to `True`. I would prefer to remove it here in favor or explicit invocation by the dev, or no invocation at all even since in 99.9% of the cases the teardown method will suffice. 

This may also be responsible for the rare failures "to detect if something is in the output and report that it has not been logged, but then I go over the logs and find out that it is there" reported by @Adamantios

**Comment by angrybayblade** [comment]
Not relevant anymore since this is not an issue in the current state of the open-autonomy repo
