### ISSUE TITLE
use `contextlib.redirect_stdout` in unit tests

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-aea#353]
In various tests we read the `sys.stdout`, e.g. in `TestConfigCases`
https://github.com/valory-xyz/open-aea/blob/1e0c3fb2d26db43f7ddc914ab1e2f8640dc81869/tests/test_test_tools/test_test_cases.py#L77-L82

sometimes mocking it via `StringIO`,
https://github.com/valory-xyz/open-aea/blob/1e0c3fb2d26db43f7ddc914ab1e2f8640dc81869/packages/valory/connections/p2p_libp2p/tests/test_build.py#L50-L57 

and these tests are always flaky. e.g.
```
FAILED tests/test_test_tools/test_test_cases.py::TestConfigCases::test_agent_nested_set_agent_crudcollection
FAILED tests/test_test_tools/test_test_cases.py::TestSendReceiveEnvelopesSkill::test_send_receive_envelope
```

 It appears that we should use a context manager to capture the output of `stdout`
https://docs.python.org/3/library/contextlib.html?highlight=stringio#contextlib.redirect_stdout

**Comment by DavidMinarsch** [comment]
Closed without full resolution

**Comment by Karrenbelt** [comment]
now addresses here: https://github.com/valory-xyz/open-aea/pull/459
