### ISSUE TITLE
Flaky test: `TestMultiAgentManagerMultiprocessMode`

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-aea#376]
CI run: https://github.com/valory-xyz/open-aea/actions/runs/3265540884/jobs/5368044602

```
FAILED tests/test_manager/test_manager.py::TestMultiAgentManagerMultiprocessMode::test_remove_running_agent
FAILED tests/test_manager/test_manager.py::TestMultiAgentManagerMultiprocessMode::test_get_overridables
```

have attached the logs in case the CI logs are no longer available by the time this gets addressed

[failures.log](https://github.com/valory-xyz/open-aea/files/9801477/failures.log)

**Comment by Karrenbelt** [comment]
CI run: https://github.com/valory-xyz/open-aea/actions/runs/3267620373/jobs/5373273948

```
FAILED tests/test_manager/test_manager.py::TestMultiAgentManagerMultiprocessMode::test_start_all
```

[failure.log](https://github.com/valory-xyz/open-aea/files/9803942/failures.log)

**Comment by angrybayblade** [comment]
One time failures, not flaky
