### ISSUE TITLE
Flaky test: `test_send_envelope_error_is_logged_by_send_loop`

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-aea#380]
CI runs: 
- https://github.com/valory-xyz/open-aea/actions/runs/3267620373/jobs/5373274399
- https://github.com/valory-xyz/open-aea/actions/runs/3268085013/jobs/5374185179

```FAILED tests/test_multiplexer.py::test_send_envelope_error_is_logged_by_send_loop```

[failure.log](https://github.com/valory-xyz/open-aea/files/9804804/failure.log)

[failure2.log](https://github.com/valory-xyz/open-aea/files/9804831/failure2.log)

**Comment by angrybayblade** [comment]
One time failure, not flaky
