### ISSUE TITLE
Flaky tests: `TestLibp2pConnectionRelayNodeRestart`

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-aea#382]
CI run: https://github.com/valory-xyz/open-aea/actions/runs/3265540884/jobs/5368044284
```
FAILED tests/test_p2p_libp2p/test_fault_tolerance.py::TestLibp2pConnectionRelayNodeRestart::test_envelope_routed_from_peer_after_relay_restart
ERROR tests/test_p2p_libp2p/test_fault_tolerance.py::TestLibp2pConnectionRelayNodeRestart::test_connection_is_established
```
[failure.log](https://github.com/valory-xyz/open-aea/files/9807260/failure2.log)

**Comment by Karrenbelt** [comment]
have not seen this re-occur in some time now. Lets keep it open for now until we evaluate outstanding issue at some point in the near future; this may comment may facilitate the decision-making process then.

**Comment by Karrenbelt** [comment]
This is effectively a `TimeoutError`. We call `queue.Queue.get()` here and the timeout is used is `10`s so that is unlike to be the issue.
https://github.com/valory-xyz/open-aea/blob/bbd8fc00e1c5ffe5c1147c2d3e342a3ecf7645cf/aea/helpers/async_friendly_queue.py#L61-L71
Hence we may look at the Multiplexer.put method invoke prior to it
https://github.com/valory-xyz/open-aea/blob/bbd8fc00e1c5ffe5c1147c2d3e342a3ecf7645cf/aea/multiplexer.py#L846-L855
which delegates to the AsyncMultiplexer.put method using the ThreadedAsyncRunner to make a thread safe call to the builtint `Queue.put_nowait`.
https://github.com/valory-xyz/open-aea/blob/bbd8fc00e1c5ffe5c1147c2d3e342a3ecf7645cf/aea/multiplexer.py#L723-L735
Noticeably a timeout for the return value of the future's result has been outcommented here in a piece of code last edited by @solarw 3 years ago, in a commit for which there is not previous version to be found via [git blame](https://github.com/fetchai/agents-aea/blame/main/aea/multiplexer.py). I don't think this is needed and the outcommented piece of code may in that case be deleted.
https://github.com/valory-xyz/open-aea/blob/bbd8fc00e1c5ffe5c1147c2d3e342a3ecf7645cf/aea/multiplexer.py#L855

In summary: I don't think there is an issue with `.put` and `.get` methods. We start the test, status is_connected, we attempt to send the message via put (queue empty) with the Threadrunner we call Queue.put -> put_nowait(). And basically get it's the same story... get with block and timeout --> .. --> .. --> Queue.get with block and timeout. 

I suggest we ask @solarw to have a look at this, as he is better acquainted with the code and concurrent programming in general. 

Tiny insignificant detail I'll leave here as well, annotation here should be `Coroutine` instead of `Awaitable`
https://github.com/valory-xyz/open-aea/blob/bbd8fc00e1c5ffe5c1147c2d3e342a3ecf7645cf/aea/helpers/async_utils.py#L258
https://github.com/valory-xyz/open-aea/blob/bbd8fc00e1c5ffe5c1147c2d3e342a3ecf7645cf/aea/helpers/async_utils.py#L328

[failure.log](https://github.com/valory-xyz/open-aea/files/10144092/failure.log)

**Comment by Karrenbelt** [comment]
on closer inspection I think this may be an issue residing on the ACN Golang-side
```
 14:04:44.896 ERR ../../../tmpgpv2kzbq/aea/api.go:392 > while processing envelope err="Sender (0x4B5A76CD59022Ed8518d5433F1c1aBE07e91Af55) must match registered address" package=AeaApi
 ```

**Comment by solarw** [comment]
tried to reproduce, no success

**Comment by angrybayblade** [comment]
Cannot reproduce
