### ISSUE TITLE
Flaky tests: `test_check_versions_negative_cannot_parse_version`

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-aea#383]
CI runs: 
- https://github.com/valory-xyz/open-aea/actions/runs/3269052222/jobs/5376484658
- https://github.com/valory-xyz/open-aea/actions/runs/3287940915/jobs/5417768414

```
FAILED tests/test_build.py::test_check_versions_negative_cannot_parse_version
```
[failure.log](https://github.com/valory-xyz/open-aea/files/9807258/failure.log)
[failure2.log](https://github.com/valory-xyz/open-aea/files/9829161/failure2.log)

**Comment by angrybayblade** [comment]
Copy of https://github.com/valory-xyz/open-aea/issues/171
