### ISSUE TITLE
Flaky tests: `tests.test_launcher.TestProcessLauncherMode`

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-aea#386]
CI run: https://github.com/valory-xyz/open-aea/actions/runs/3287940915/jobs/5417768286

```
FAILED tests/test_launcher.py::TestProcessLauncherMode::test_start_stop
```

[failures.log](https://github.com/valory-xyz/open-aea/files/9829203/failures.log)

**Comment by angrybayblade** [comment]
One time failure, not flaky
