### ISSUE TITLE
Flaky tests: `test_ethereum.py::test_try_get_gas_pricing_poa`

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-aea#395]
CI run: https://github.com/valory-xyz/open-aea/actions/runs/3302669282/jobs/5449792777
```
FAILED plugins/aea-ledger-ethereum/tests/test_ethereum.py::test_try_get_gas_pricing_poa[strategy0]
```
[failure.log](https://github.com/valory-xyz/open-aea/files/9844440/failure.log)

**Comment by angrybayblade** [comment]
Not flaky anymore
