### ISSUE TITLE
Send to IPFS without storing locally

### ISSUE THREAD

**Issue by dvilelaf** [valory-xyz/open-aea#401]
**Is your feature request related to a problem? Please describe.**
IPFS tools currently require objects to be stored first.

**Describe the solution you'd like**
In many cases we just care about sending objects to IPFS and not about storing locally. If storing is completely required by IPFS, then we can extend our tools to handle it automatically and create temporal paths that are cleaned after sending.

**Comment by Adamantios** [comment]
We are currently utilizing `add`:

https://github.com/valory-xyz/open-aea/blob/bfe783f040a044ea4bf46a7ea3728ede97ae7df8/plugins/aea-cli-ipfs/aea_cli_ipfs/ipfs_utils.py#L256

We can also use `add_bytes`, `add_str` and `add_json` that the IPFS `Client` class provides.
That way, we can remove the implementation for storing and loading JSON files on the autonomy side and we could also send images directly with the `add_bytes`.

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-aea/pull/473
