### ISSUE TITLE
flaky test interaction: `test_supervisor_not_started` & `test_cancelled_during_start_agent_loop`

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-aea#408]
CI runs:
- https://github.com/valory-xyz/open-aea/actions/runs/3338478396/jobs/5526429003
- https://github.com/valory-xyz/open-aea/actions/runs/3337137634/jobs/5523231012
- https://github.com/valory-xyz/open-aea/actions/runs/3337137634/jobs/5523230658

```
_________________________ test_supervisor_not_started __________________________

    def test_supervisor_not_started():
        """Test that TestThreadGuard supervisor thread not started."""
        timeout = 0.1
        sleep_time = 0.5
    
        exec_limiter = ExecTimeoutThreadGuard(timeout)
    
        with exec_limiter as exec_limit:
>           assert not exec_limiter._future_guard_task
E           assert not <Future at 0x7f44006b2f80 state=pending>
E            +  where <Future at 0x7f44006b2f80 state=pending> = <aea.helpers.exec_timeout.ExecTimeoutThreadGuard object at 0x7f44006b0100>._future_guard_task

tests/test_helpers/test_exec_timeout.py:179: AssertionError
...
FAILED tests/test_helpers/test_exec_timeout.py::test_supervisor_not_started
```

[failure.log](https://github.com/valory-xyz/open-aea/files/9881138/failure.log)

**Comment by Karrenbelt** [comment]
was attempted to be resolved in #413 but to no avail. A causal relationship with a test recently introduced in PR #403 seems to have been established. Currently this test is skipped, which will need to be addressed as part of this ticket.

**Comment by solarw** [comment]
suppose it's a quite tricky function and recommend to remove it completely.

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-aea/pull/598
