### ISSUE TITLE
Check for packages requires indirect import

### ISSUE THREAD

**Issue by Adamantios** [valory-xyz/open-aea#427]
https://github.com/valory-xyz/price-oracle/pull/10#discussion_r1013065454

**Comment by solarw** [comment]
issue opened by mistake.
checked code in history and https://github.com/valory-xyz/price-oracle/blob/91426a692427556ef1bc045052a5c56000d69fd0/packages/valory/contracts/offchain_aggregator/contract.py#L29

tool works well.
nothing to fix

**Comment by Adamantios** [comment]
Thanks! Closing the issue because the `eth-abi` is directly referenced in the code, so the check is correct.
