### ISSUE TITLE
storing file system paths

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-aea#440]
We currently store paths to specific directories or files as part of configurations. However, these will not be useful on another operating system. 

Take for example this series of paths for example (the POSIX-compliant version of which is used [here](https://github.com/valory-xyz/open-aea/blob/8c8b8de4b5764d9cd1f095760608a80a76193363/tests/test_configurations/test_base.py#L1136-L1162)).
```
raw_windows_paths = [
    r"C:\Documents\Newsletters\Summer2018.pdf",
    r"\Program Files\Custom Utilities\StringFinder.exe",
    r"2018\January.xlsx",
    r"..\Publications\TravelBrochure.pdf",
    r"C:\Projects\apilibrary\apilibrary.sln",
    r"C:Projects\apilibrary\apilibrary.sln",
    r"c:\temp\test-file.txt",
    r"\\127.0.0.1\c$\temp\test-file.txt",
    r"\\LOCALHOST\c$\temp\test-file.txt",
    r"\\.\c:\temp\test-file.txt",
    r"\\?\c:\temp\test-file.txt",
    r"\\.\UNC\LOCALHOST\c$\temp\test-file.txt",
    r"jquery-1.1.1.js",
    r"jquery-1.1.1.min.js",
    r"jquery-1.1.1-vsdoc.js",
    r"jquery-1.2.1-vsdoc.js",
    r"jquery-1.2.1.js",
    r"jquery-1.2.1.min.js",
]
```
The first one of these will already be parsed with additional escape characters on UNIX, and not be recognized as a proper path. Hence the conversion of these paths to proper POSIX-compliant format can only be tested on Windows in the first place, and reading any such raw strings from a serialized piece of data coming from Windows that was not properly serialized to POSIX will not be parsed correctly.
```
>>> r"C:\Documents\Newsletters\Summer2018.pdf"
'C:\\Documents\\Newsletters\\Summer2018.pdf'
>>> Path(r"C:\Documents\Newsletters\Summer2018.pdf").parts
('C:\\Documents\\Newsletters\\Summer2018.pdf',)
```

We should not store the root of the paths, as these will be both operating and user specific.  The root might be the repository, but it might as well be a directory. We may chose to encode this with a placeholder, or akin an environmental variable (e.g. `{ROOT_DIR}`). We use such derived from `os.path.dirname(inspect.getfile(inspect.currentframe()))` in our tests

**Comment by solarw** [comment]
@DavidMinarsch @angrybayblade 
not sure i got this case correct, but i see that path specification is up to the end user(developer).
so if developer or user wants to sed `aea add-key cosmos /root/dir/` it's not a framework problem

probably we can restrict usage of absolute paths in the cli, not sure it worths it

**Comment by angrybayblade** [comment]
@solarw What are the places where we store the paths in the component configs, some places I know where we store path as a part of the component config

To store keys and certificate paths, here we add these keys and certificates to the config at the runtime so they're relative by default.

To store fingerprint records, here they are relative by default and needs to be relative.

Any other places you know where we can face this absolute vs. relative path strings issue?

**Comment by angrybayblade** [comment]
I'm closing this issue because this does not look like a framework concern
