### ISSUE TITLE
YAML data type serialization

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-aea#452]
We currently do not support all data types - https://yaml.org/spec/1.2.2/#chapter-2-language-overview

This can lead to serialization issues where we are not explicit, e.g. where in a conditional branching the else clause leads to string casting. Moreover, the [environmental variable parser](https://github.com/valory-xyz/open-aea/blob/main/aea/helpers/env_vars.py) does not support them (also see [constants](https://github.com/valory-xyz/open-aea/blob/main/aea/helpers/constants.py)).

``` 
if isinstance(value, (int, float, str, bytes, ...)): 
    ... 
elif isinstance(value, typing.Mapping): 
    ... 
elif isinstance(value, typing.Iterable):
    ... 
else: 
    raise
```

**Comment by angrybayblade** [comment]
Not relevant
