### ISSUE TITLE
agent subprocess termination

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-aea#474]
We have witnessed that an agent process might not terminate after a kill signal with a 30 second timeout. 

1. "The child process is not killed if the timeout expires, so in order to cleanup properly a well-behaved application should kill the child process and **finish communication**" - [reference](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate)
2. We should consider running the agent in a separate process group. This will prevent orphan (zombie) processes in case the agent spawn any subprocesses. - [reference](https://stackoverflow.com/questions/4789837/how-to-terminate-a-python-subprocess-launched-with-shell-true/4791612#4791612)
- we may also inspect the subprocess termination logic in the [psutil library](https://github.com/giampaolo/psutil) for details of their implementation.

**Comment by solarw** [comment]
suppose it's good to make a test that checks agent terminated properly, without any subprocesses left

https://github.com/valory-xyz/open-aea/pull/563 partially fixes for windows.

not sure issue presents for liunx,mac. need to check

**Comment by angrybayblade** [comment]
Addressed
