### ISSUE TITLE
suggestion: `check_test_cwd` --> `restore_cwd`

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-aea#487]
We may consider changing the following auto-use fixtures to restore the original directory instead of raising. This will annihilate the need to a developer to implement such logic as part of the `setup_class`, `setup`, `teardown` and/or `teardown_class` logic.

https://github.com/valory-xyz/open-aea/blob/9d9dbafbfbd9fbdcc71f5d2c2f5caf27b9a87917/tests/conftest.py#L823-L830
https://github.com/valory-xyz/open-aea/blob/9d9dbafbfbd9fbdcc71f5d2c2f5caf27b9a87917/tests/conftest.py#L833-L844

**Comment by DavidMinarsch** [comment]
Disagree. This obfuscates when `cwd` changes occur, unlike the current approach where it is explicit from the test class.
