### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by DavidMinarsch** [valory-xyz/open-aea#517]
**Is your feature request related to a problem? Please describe.**
Multiple flaky tests:
- tests/test_manager/test_manager.py::TestMultiAgentManagerMultiprocessModeWithPassword::test_start_all at https://github.com/valory-xyz/open-aea/actions/runs/3809364801/jobs/6480718908
- https://github.com/valory-xyz/open-aea/actions/runs/3809364801/jobs/6480718945 multiple p2p_libp2p 
- tests/test_manager/test_manager.py::TestMultiAgentManagerMultiprocessMode::test_remove_running_agent at https://github.com/valory-xyz/open-aea/actions/runs/3809364801/jobs/6480718992
- at https://github.com/valory-xyz/open-aea/actions/runs/3809364801/jobs/6480719350
FAILED plugins/aea-ledger-fetchai/tests/test_cosmos.py::test_get_handle_transaction
FAILED plugins/aea-ledger-fetchai/tests/test_cosmos.py::test_get_packed_send_msg
FAILED plugins/aea-ledger-fetchai/tests/test_cosmos.py::test_get_deploy_transaction
FAILED plugins/aea-ledger-fetchai/tests/test_cosmos.py::test_get_multi_transaction
FAILED plugins/aea-ledger-fetchai/tests/test_cosmos.py::test_get_transfer_transaction
- tests/test_configurations/test_data_types.py::test_type_comparison at https://github.com/valory-xyz/open-aea/actions/runs/3809364801/jobs/6480719482

**Describe the solution you'd like**
Fix

**Comment by solarw** [comment]
```

    def MergeFrom(self, msg):
      if not isinstance(msg, cls):
>       raise TypeError(
            'Parameter to MergeFrom() must be instance of same class: '
            'expected %s got %s.' % (_FullyQualifiedClassName(cls),
                                     _FullyQualifiedClassName(msg.__class__)))
E       TypeError: Parameter to MergeFrom() must be instance of same class: expected cosmos.base.v1beta1.coin_pb2.Coin got cosmos.base.v1beta1.coin_pb2.Coin.
```

this is the issue with double module import and mostly protobuf problem, cause it has some tricky import system

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-aea/pull/567
