### ISSUE TITLE
Investigate and fix the `update_plugin_versions.py` script

### ISSUE THREAD

**Issue by angrybayblade** [valory-xyz/open-aea#569]
The script does not perform proper version updates when running against post releases

To reproduce the issue

- Set the plugin version to `1.28.0.post1` on `plugins/aea-cli-ipfs/setup.py:31` and `deploy-image/Dockerfile:19`
- Run `python scripts/update_plugin_versions.py --update "open-aea-cli-ipfs,1.29.0"`

This bumps the version to `1.29.0` in the `setup.py` but in the `Dockerfile` it updates the version to `1.29.0.post1`

**Comment by solarw** [comment]
@angrybayblade 

the problem - is manual edit of the docker file.
bump from 1.28.0 to 1.28.0.post1 makes line `RUN pip install --upgrade --force-reinstall open-aea[all]==1.28.0.post1 "open-aea-cli-ipfs<2.0.0,>=1.28.0"`

not `RUN pip install --upgrade --force-reinstall open-aea[all]==1.28.0.post1 "open-aea-cli-ipfs<2.0.0,>=1.28.0.post1"`

and it's ok to the algo. 
looks .post1 was added manually that caused script problems
