### ISSUE TITLE
Scaffolding using `tlr` creates `pycache` folder & doesn't update dev packages!

### ISSUE THREAD

**Issue by DavidMinarsch** [valory-xyz/open-aea#586]
**Is your feature request related to a problem? Please describe.**
Scaffolding tlr creates pycache folder & doesn't update dev packages!

**Describe the solution you'd like**
No `pycache` folder should be present and the dev packages should be updated.

**Comment by angrybayblade** [comment]
Addressed https://github.com/valory-xyz/open-aea/pull/635
