### ISSUE TITLE
aea generate-all-protocols to make one protocol generation

### ISSUE THREAD

**Issue by solarw** [valory-xyz/open-aea#612]
add `aea generate-protocol [protocol name]`
to make easier to generate on protocol needed.
can be useful for developing in local registry.

**Comment by angrybayblade** [comment]
We already have support for generating only one protocol at a time using `aea generate protocol`, unfortunately it did not support generating the protocol to local registry which is fixed on https://github.com/valory-xyz/open-aea/pull/632
