### ISSUE TITLE
A ledger should be installed by default OR include more helpful error messages.

### ISSUE THREAD

**Issue by jmoreira-valory** [valory-xyz/open-aea#650]
**Is your feature request related to a problem? Please describe.**
When installing open aea (or open autonomy) no ledger is installed by default. This causes the following sequence of events for a user trying to use `aea generate-key ethereum -n 4`:

```
aea generate-key ethereum -n 4
Usage: aea generate-key [OPTIONS] TYPE FILE
Try 'aea generate-key --help' for help.

Error: Invalid value for 'TYPE': 'ethereum' is not 'all'.
```

This message actually seems to confuse the user by suggesting that changing `ethereum` by `all` will fix the error message. However,

```
aea generate-key all -n 4
Traceback (most recent call last):

(...Long exception stack trace...)

  File "/home/<user>/.local/share/virtualenvs/open-operator-watchtower-Fee1W5a_/lib/python3.10/site-packages/aea/crypto/registries/base.py", line 269, in _get_spec
    raise AEAException("Item not registered with id '{}'.".format(item_id))
aea.exceptions.AEAException: Item not registered with id 'all'.
```

The user has no indication here on what is it causing the error and how to fix it.

**Describe the solution you'd like**
Either install a ledger by default, or show an error message indicating that no ledger is installed. No exceptions should be received by the user using this command.

**Describe alternatives you've considered**
--

**Additional context**
This also happens with open-autonomy.

**Comment by angrybayblade** [comment]
A ledger plugin should not be installed with either open-aea or open-autonomy since these frameworks are supposed to be ledger agnostic
