### ISSUE TITLE
Improve package dependency checks / unclear error message

### ISSUE THREAD

**Issue by dvilelaf** [valory-xyz/open-aea#657]
**Describe the bug**
Packages specify their dependencies in their corresponding yaml files. When one of this dependencies is used but not added to connection.yaml (for example), service fail to run with the "container unhealthy" error. I think we should detect this issues earlier.

**Comment by DavidMinarsch** [comment]
Looks related to the check-dependencies issue https://github.com/valory-xyz/open-aea/issues/578
