### ISSUE TITLE
Support Solana Versioned Transactions

### ISSUE THREAD

**Issue by Dassy23** [valory-xyz/open-aea#697]
**Describe the bug**
Current setup does not support Solana's new versioned transactions. https://docs.solana.com/developing/versioned-transactions

Some areas to fix
- add maxSupportedTransactionVersion field to get get_transaction functions
```

      transaction_receipt = solana_api.api.get_transaction(
                Signature.from_string(transaction_digest),
                max_supported_transaction_version=100
            ) 
```
            
- signing will need to be able to handle as well, here is some sample code to add nonce, and sign a versionedtx 

```
       recent_blockhash = self.ledger_api.api.get_latest_blockhash().value.blockhash
        txn['message'][1]['recentBlockhash'] = json.loads(recent_blockhash.to_json())
        msg = MessageV0.from_json(json.dumps(txn['message'][1]))
        signed_transaction = VersionedTransaction(msg,[payer.entity])

```
- function to convert dict tx to versiontx and back. There is a bug in the solders lib that doesnt allow direct from_json(). But you can pull out the versioned msg (txn['message'][1]) and load it into a new versioned tx

**Comment by 8ball030** [comment]
@angrybayblade 
This is kind of blocking unfortunately :'( 
I suspect it might be an issue for further work to be done on the agent staking side as well.

**Comment by DavidMinarsch** [comment]
Thanks - will start this in a week's time. Next week is unfortunately not possible.
