### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by Joj501** [valory-xyz/open-aea#765]
**Describe the bug**

**To Reproduce**
2. Do '....'
3. See error '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - AEA Version [e.g. 1.0.0]

**Additional context**

**Comment by Adamantios** [comment]
I’m closing this issue for now as it doesn’t contain enough information for us to proceed. Please feel free to reopen it with more details about the feature or change you have in mind. Thanks!
