### ISSUE TITLE
Implement demonstration of using a protocol as a demo

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-aea#90]
**Is your feature request related to a problem? Please describe.**
Based on feedback from participants, we could do with more demos.
Additionally, [https://github.com/valory-xyz/open-aea/pull/89](pr) proposes removing a protocol demonstration

**Describe the solution you'd like**
- possible integration of the sushi farmer into the demos
- possible abci protocol example

**Comment by DavidMinarsch** [comment]
We have many demos with different types of packages
